stages:
    - deploy

pages:
    stage: deploy
    image: python
    script:
        - pip install -U sphinx
        - pip install --upgrade recommonmark
        - pip install sphinx_rtd_theme
        - cd docs
        - make html
        - mv build/html ../public
        - cd ..
        - find . ! -name 'public' -exec rm -rf {} +
        - find . -type d -exec chmod 755 {} \;
        - find . -type f -exec chmod 644 {} \;
    artifacts:
        paths:
            - public
