stages:
    - deploy

pages:
    stage: deploy
    image: python
    script:
        - pip install -U sphinx sphinx_rtd_theme myst-parser
        - cd docs
        - make html
        - mv build/html ../public
    artifacts:
        paths:
            - public
